---
- hosts: all
  vars:
    home_dir: /home/vagrant
    bin_dir: "{{ home_dir }}/bin"
    src_dir: "{{ home_dir }}/sources"
  tasks:
    - name: Install SELinux bindings
      become: yes
      become_method: sudo
      dnf: name={{item}} state=latest
      with_items:
        - libselinux-python
        - libselinux-python3
    - name: Add BCC repository
      become: yes
      become_method: sudo
      copy:
        content: |
          [iovisor]
          baseurl=https://repo.iovisor.org/yum/nightly/f25/$basearch
          enabled=1
          gpgcheck=0
        dest: /etc/yum.repos.d/iovisor.repo
        owner: root
        group: root
        mode: 0644
    - name: Add Docker CE repository
      become: yes
      become_method: sudo
      block:
        - rpm_key:
            key: https://download.docker.com/linux/fedora/gpg
        - get_url:
            url: https://download.docker.com/linux/fedora/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
            owner: root
            group: root
            mode: 0644
    - name: Add Golang repository
      become: yes
      become_method: sudo
      block:
        - get_url:
            url: https://mirror.go-repo.io/fedora/RPM-GPG-KEY-GO-REPO
            dest: /tmp/go-repo.gpg
        - rpm_key:
            key: /tmp/go-repo.gpg
        - get_url:
            url: https://mirror.go-repo.io/fedora/go-repo.repo
            dest: /etc/yum.repos.d/go-repo.repo
            owner: root
            group: root
            mode: 0644
    - name: Install tools from Fedora repos
      become: yes
      become_method: sudo
      dnf: name={{item}} state=latest
      with_items:
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        - kernel-devel
        - kernel-headers
        - perf
        - bcc-tools
        - rkt
        - docker-ce
        - screen
        - tmux
        - cmake
        - git
        - gcc
        - gcc-c++
        - golang
    - name: Install shell extensions
      become: yes
      become_method: sudo
      copy:
        src: /vagrant/profile_ext.sh
        dest: /etc/profile.d/sre.sh
        owner: root
        group: root
        mode: 0755
    - name: Ensure the user has a bin directory
      file:
        path: "{{ bin_dir }}"
        state: directory
    - name: Install BCC runner
      copy:
        src: /vagrant/bccrun
        dest: "{{ bin_dir }}/bccrun"
        mode: 0755
    - name: Install perf-agent-map
      block:
        - git:
            repo: https://github.com/jvm-profiling-tools/perf-map-agent.git
            dest: "{{ src_dir }}/perf-map-agent"
          register: pmaclone
        - file:
            path: "{{ src_dir }}/perf-map-agent/Makefile"
            state: absent
          when: pmaclone.before != pmaclone.after
        - command: cmake .
          args:
            chdir: "{{ src_dir }}/perf-map-agent"
            creates: "{{ src_dir }}/perf-map-agent/Makefile"
        - command: make
          args:
            chdir: "{{ src_dir }}/perf-map-agent"
        - file:
            src: "{{ src_dir }}/perf-map-agent/bin/{{ item }}"
            dest: "{{ bin_dir }}/{{ item }}"
            state: link
          with_items:
            - perf-java-top
            - perf-java-report-stack
            - perf-java-record-stack
            - perf-java-flames
    - name: Install FlameGraph
      block:
        - git:
            repo: https://github.com/brendangregg/FlameGraph
            dest: "{{ home_dir }}/sources/FlameGraph"
        - file:
            src: "{{ home_dir }}/sources/FlameGraph/{{ item }}"
            dest: "{{ home_dir }}/bin/{{ item }}"
            state: link
          with_items:
            - stackcollapse.pl
            - stackcollapse-perf.pl
            - stackcollapse-pmc.pl
            - stackcollapse-stap.pl
            - stackcollapse-instruments.pl
            - stackcollapse-vtune.pl
            - stackcollapse-ljp.awk
            - stackcollapse-jstack.pl
            - stackcollapse-gdb.pl
            - stackcollapse-go.pl
            - stackcollapse-vsprof.pl
            - flamegraph.pl
